### ISSUE TITLE
Feature request: Expose beta_est as a user argument in solve_wg_modes

### ISSUE THREAD

**Issue by ianwilliamson** [YuJerryShi/fdfd_suite#1]
I think a great feature would be for **beta_est** to be exposed as a user-facing argument. The current implementation would be a great default, but because there are structures supporting modes of interest at various _depths_ below the light line, this could be useful for targeting them.

**Comment by YuJerryShi** [comment]
Thanks for the suggestion, Ian! I have included an optional argument for **fdfd_wg_modes** called **beta_scale**. This scales the initial guess of beta in the mode solver by **beta_scale**, and it is by default set to 2. I have further added a file in the "examples" folder named "MIM_slot_waveguide.m", where the **beta_scale** is set to 2.5. Hope this helps!
